apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: strimzi-kafka-operator
  namespace: %{ if isOpenshift }openshift-%{ endif }operators
spec:
  channel: ${channel}
  name: strimzi-kafka-operator
  source: ${operatorSource}
  sourceNamespace: ${sourceNamespace}
 %{ if isOpenshift }
  installPlanApproval: Automatic
  startingCSV: ${ startingCSV }
 %{ endif }
